#!/usr/bin/python
import sys
sys.path.insert(0, "../../../")
sys.path.insert(0, "./script/")

import lib 
from lib.baselib import execute_check, MismatchException

#
# Run and check
#
gdb.Breakpoint("test.t:test1")

try:
	execute_check("run",  29 )
	execute_check("s", 31)
	execute_check("s", 2, index = 0)
	execute_check("s", 4, index = 8, pre1 = 0, pre2 = 0)
	execute_check("s", 7, index = 8, pre1 = 0, pre2 = 0)
	execute_check("s", 8, index = 8, ans = 0, pre1 = 0, pre2 = 0)
	execute_check("s", 9, index = 8, ans = 0, pre1 = 1, pre2 = 0)
	execute_check("s", 10, index = 8, ans = 0, pre1 = 1, pre2 = 0)
	execute_check("s", 12, index = 8, i = 2, ans = 0, pre1 = 1, pre2 = 0)
	execute_check("s", 13, index = 8, i = 2, ans = 1, pre1 = 1, pre2 = 0)
	execute_check("s", 14, index = 8, i = 2, ans = 1, pre1 = 1, pre2 = 1)
	execute_check("s", 15, index = 8, i = 2, ans = 1, pre1 = 1, pre2 = 1)
	execute_check("s", 10, index = 8, i = 2, ans = 1, pre1 = 1, pre2 = 1)
	execute_check("s", 12, index = 8, i = 3, ans = 1, pre1 = 1, pre2 = 1)
	execute_check("s", 13, index = 8, i = 3, ans = 2, pre1 = 1, pre2 = 1)
	execute_check("s", 14, index = 8, i = 3, ans = 2, pre1 = 1, pre2 = 1)
	execute_check("s", 15, index = 8, i = 3, ans = 2, pre1 = 2, pre2 = 1)
	execute_check("s", 10, index = 8, i = 3, ans = 2, pre1 = 2, pre2 = 1)
	execute_check("s", 12, index = 8, i = 4, ans = 2, pre1 = 2, pre2 = 1)
	execute_check("s", 13, index = 8, i = 4, ans = 3, pre1 = 2, pre2 = 1)
	execute_check("s", 14, index = 8, i = 4, ans = 3, pre1 = 2, pre2 = 2)
	execute_check("s", 15, index = 8, i = 4, ans = 3, pre1 = 3, pre2 = 2)
	execute_check("s", 10, index = 8, i = 4, ans = 3, pre1 = 3, pre2 = 2)
	execute_check("s", 12, index = 8, i = 5, ans = 3, pre1 = 3, pre2 = 2)
	execute_check("s", 13, index = 8, i = 5, ans = 5, pre1 = 3, pre2 = 2)
	execute_check("s", 14, index = 8, i = 5, ans = 5, pre1 = 3, pre2 = 3)
	execute_check("s", 15, index = 8, i = 5, ans = 5, pre1 = 5, pre2 = 3)
	execute_check("s", 10, index = 8, i = 5, ans = 5, pre1 = 5, pre2 = 3)
	execute_check("s", 12, index = 8, i = 6, ans = 5, pre1 = 5, pre2 = 3)
	execute_check("s", 13, index = 8, i = 6, ans = 8, pre1 = 5, pre2 = 3)
	execute_check("s", 14, index = 8, i = 6, ans = 8, pre1 = 5, pre2 = 5)
	execute_check("s", 15, index = 8, i = 6, ans = 8, pre1 = 8, pre2 = 5)
	execute_check("s", 10, index = 8, i = 6, ans = 8, pre1 = 8, pre2 = 5)
	execute_check("s", 12, index = 8, i = 7, ans = 8, pre1 = 8, pre2 = 5)
	execute_check("s", 13, index = 8, i = 7, ans = 13, pre1 = 8, pre2 = 5)
	execute_check("s", 14, index = 8, i = 7, ans = 13, pre1 = 8, pre2 = 8)
	execute_check("s", 15, index = 8, i = 7, ans = 13, pre1 = 13, pre2 = 8)
	execute_check("s", 10, index = 8, i = 7, ans = 13, pre1 = 13, pre2 = 8)
	execute_check("s", 12, index = 8, i = 8, ans = 13, pre1 = 13, pre2 = 8)
	execute_check("s", 13, index = 8, i = 8, ans = 21, pre1 = 13, pre2 = 8)
	execute_check("s", 14, index = 8, i = 8, ans = 21, pre1 = 13, pre2 = 13)
	execute_check("s", 15, index = 8, i = 8, ans = 21, pre1 = 21, pre2 = 13)
	execute_check("s", 10, index = 8, i = 8, ans = 21, pre1 = 21, pre2 = 13)
	execute_check("s", 16, index = 8, i = 9, ans = 21, pre1 = 21, pre2 = 13)
	execute_check("s", 17, index = 8)
	execute_check("s", 32, x = 21)
	execute_check("s", 19)
	execute_check("s", 21, index = 8)
	execute_check("s", 23, index = 8)
	execute_check("s", 19)
	execute_check("s", 21, index = 7)
	execute_check("s", 23, index = 7)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 6)
	execute_check("s", 23, index = 6)
	execute_check("s", 19)
	execute_check("s", 21, index = 5)
	execute_check("s", 23, index = 5)
	execute_check("s", 19)
	execute_check("s", 21, index = 4)
	execute_check("s", 23, index = 4)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 3)
	execute_check("s", 23, index = 3)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 2)
	execute_check("s", 23, index = 2)
	execute_check("s", 19)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 19)
	execute_check("s", 21, index = 0)
	execute_check("s", 24, index = 0)
	execute_check("s", 23, index = 2)
	execute_check("s", 24, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 23, index = 3)
	execute_check("s", 24, index = 3)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 2)
	execute_check("s", 23, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 0)
	execute_check("s", 24, index = 0)
	execute_check("s", 23, index = 2)
	execute_check("s", 24, index = 2)
	execute_check("s", 23, index = 4)
	execute_check("s", 24, index = 4)
	execute_check("s", 19)
	execute_check("s", 21, index = 3)
	execute_check("s", 23, index = 3)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 2)
	execute_check("s", 23, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 0)
	execute_check("s", 24, index = 0)
	execute_check("s", 23, index = 2)
	execute_check("s", 24, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 23, index = 3)
	execute_check("s", 24, index = 3)
	execute_check("s", 23, index = 5)
	execute_check("s", 24, index = 5)
	execute_check("s", 19)
	execute_check("s", 21, index = 4)
	execute_check("s", 23, index = 4)
	execute_check("s", 19)
	execute_check("s", 21, index = 3)
	execute_check("s", 23, index = 3)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 2)
	execute_check("s", 23, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 0)
	execute_check("s", 24, index = 0)
	execute_check("s", 23, index = 2)
	execute_check("s", 24, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 23, index = 3)
	execute_check("s", 24, index = 3)
	execute_check("s", 19)
	execute_check("s", 21, index = 2)
	execute_check("s", 23, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 0)
	execute_check("s", 24, index = 0)
	execute_check("s", 23, index = 2)
	execute_check("s", 24, index = 2)
	execute_check("s", 23, index = 4)
	execute_check("s", 24, index = 4)
	execute_check("s", 23, index = 6)
	execute_check("s", 24, index = 6)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 5)
	execute_check("s", 23, index = 5)
	execute_check("s", 19)
	execute_check("s", 21, index = 4)
	execute_check("s", 23, index = 4)
	execute_check("s", 19)
	execute_check("s", 21, index = 3)
	execute_check("s", 23, index = 3)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 2)
	execute_check("s", 23, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 0)
	execute_check("s", 24, index = 0)
	execute_check("s", 23, index = 2)
	execute_check("s", 24, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 23, index = 3)
	execute_check("s", 24, index = 3)
	execute_check("s", 19)
	execute_check("s", 21, index = 2)
	execute_check("s", 23, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 0)
	execute_check("s", 24, index = 0)
	execute_check("s", 23, index = 2)
	execute_check("s", 24, index = 2)
	execute_check("s", 23, index = 4)
	execute_check("s", 24, index = 4)
	execute_check("s", 19)
	execute_check("s", 21, index = 3)
	execute_check("s", 23, index = 3)
	execute_check("s", 19)
	execute_check("s", 21, index = 2)
	execute_check("s", 23, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 0)
	execute_check("s", 24, index = 0)
	execute_check("s", 23, index = 2)
	execute_check("s", 24, index = 2)
	execute_check("s", 19)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 23, index = 3)
	execute_check("s", 24, index = 3)
	execute_check("s", 23, index = 5)
	execute_check("s", 24, index = 5)
	execute_check("s", 23, index = 7)
	execute_check("s", 24, index = 7)
	execute_check("s", 19)
	execute_check("s", 21, index = 6)
	execute_check("s", 23, index = 6)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 5)
	execute_check("s", 23, index = 5)
	execute_check("s", 19)
	execute_check("s", 21, index = 4)
	execute_check("s", 23, index = 4)
	execute_check("s", 19)
	execute_check("s", 21, index = 3)
	execute_check("s", 23, index = 3)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 2)
	execute_check("s", 23, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 0)
	execute_check("s", 24, index = 0)
	execute_check("s", 23, index = 2)
	execute_check("s", 24, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 23, index = 3)
	execute_check("s", 24, index = 3)
	execute_check("s", 19)
	execute_check("s", 21, index = 2)
	execute_check("s", 23, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 0)
	execute_check("s", 24, index = 0)
	execute_check("s", 23, index = 2)
	execute_check("s", 24, index = 2)
	execute_check("s", 23, index = 4)
	execute_check("s", 24, index = 4)
	execute_check("s", 19)
	execute_check("s", 21, index = 3)
	execute_check("s", 23, index = 3)
	execute_check("s", 19)
	execute_check("s", 21, index = 2)
	execute_check("s", 23, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 0)
	execute_check("s", 24, index = 0)
	execute_check("s", 23, index = 2)
	execute_check("s", 24, index = 2)
	execute_check("s", 19)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 23, index = 3)
	execute_check("s", 24, index = 3)
	execute_check("s", 23, index = 5)
	execute_check("s", 24, index = 5)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 4)
	execute_check("s", 23, index = 4)
	execute_check("s", 19)
	execute_check("s", 21, index = 3)
	execute_check("s", 23, index = 3)
	execute_check("s", 19)
	execute_check("s", 21, index = 2)
	execute_check("s", 23, index = 2)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 19, index = 0)
	execute_check("s", 21, index = 0)
	execute_check("s", 24, index = 0)
	execute_check("s", 23, index = 2)
	execute_check("s", 24, index = 2)
	execute_check("s", 19)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 23, index = 3)
	execute_check("s", 24, index = 3)
	execute_check("s", 19)
	execute_check("s", 21, index = 2)
	execute_check("s", 23, index = 2)
	execute_check("s", 19)
	execute_check("s", 21, index = 1)
	execute_check("s", 24, index = 1)
	execute_check("s", 19)
	execute_check("s", 21, index = 0)
	execute_check("s", 24, index = 0)
	execute_check("s", 23, index = 2)
	execute_check("s", 24, index = 2)
	execute_check("s", 23, index = 4)
	execute_check("s", 24, index = 4)
	execute_check("s", 23, index = 6)
	execute_check("s", 24, index = 6)
	execute_check("s", 23, index = 8)
	execute_check("s", 24, index = 8)
	execute_check("s", 32, x = 21)
	execute_check("s", 33, x = 21, y = 21)
	execute_check("s", 35, x = 21, y = 21, result = 0)
	execute_check("s", 37, x = 21, y = 21, result = 0)
	execute_check("s", 38, x = 21, y = 21, result = 1)
	execute_check("s", 43, x = 21, y = 21, result = 1)
	execute_check("s", 44)
	gdb.execute('quit')
except MismatchException, e:
	gdb.execute('quit 1') # quit with error code

