/**
 * Zillians MMO
 * Copyright (C) 2007-2011 Zillians.com, Inc.
 * For more information see http://www.zillians.com
 *
 * Zillians MMO is the library and runtime for massive multiplayer online game
 * development in utility computing model, which runs as a service for every
 * developer to build their virtual world running on our GPU-assisted machines.
 *
 * This is a close source library intended to be used solely within Zillians.com
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef ZILLIANS_LANGUAGE_LOGCONTEXT_H_
#define ZILLIANS_LANGUAGE_LOGCONTEXT_H_

#include "core/Prerequisite.h"
#include "language/tree/ASTNodeFactory.h"
#include "language/GlobalContext.h"

namespace zillians { namespace language { namespace stage {

/// Store the error info generated by semantic and parsing check
struct LogInfoContext
{
	LogInfoContext(const std::wstring& log_level, const std::wstring& log_id, const std::map<std::wstring, std::wstring>& parameters) :
		log_level(log_level), log_id(log_id), parameters(parameters)
	{
	}

	static LogInfoContext* get(tree::ASTNode* node)
	{
		return node->get<LogInfoContext>();
	}

	static void set(tree::ASTNode* node, LogInfoContext* ctx)
	{
		node->set<LogInfoContext>(ctx);
	}

	bool operator==(const LogInfoContext& rhs) const
	{
		return log_level == rhs.log_level &&
			   log_id == rhs.log_id &&
			   parameters == rhs.parameters ;
	}

	bool operator!=(const LogInfoContext& rhs) const
	{
		return ! operator==(rhs);
	}

	std::wstring log_level;
	std::wstring log_id;
	std::map<std::wstring, std::wstring> parameters;
};

} } }

#endif /* ZILLIANS_LANGUAGE_LOGCONTEXT_H_ */
