/**
 * Zillians MMO
 * Copyright (C) 2007-2011 Zillians.com, Inc.
 * For more information see http://www.zillians.com
 *
 * Zillians MMO is the library and runtime for massive multiplayer online game
 * development in utility computing model, which runs as a service for every
 * developer to build their virtual world running on our GPU-assisted machines.
 *
 * This is a close source library intended to be used solely within Zillians.com
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef ZILLIANS_LANGUAGE_ERRORINFOCONTEXT_H_
#define ZILLIANS_LANGUAGE_ERRORINFOCONTEXT_H_

#include "core/Prerequisite.h"
#include "language/tree/ASTNodeFactory.h"
#include "language/GlobalContext.h"
#include "language/stage/generator/detail/LLVMHeaders.h"

namespace zillians { namespace language { namespace stage {

/// Store the error info generated by semantic and parsing check
struct ErrorInfoContext
{
	typedef std::map<std::string, std::string>	parameter_type_t;

	ErrorInfoContext(std::string& log_level, std::string& log_id, std::vector<parameter_type_t>& parameters) :
		log_level(log_level), log_id(log_id), parameters(parameters)
	{
	}

	static ErrorInfoContext* get(tree::ASTNode* node)
	{
		return node->get<ErrorInfoContext>();
	}

	static void set(tree::ASTNode* node, ErrorInfoContext* ctx)
	{
		node->set<ErrorInfoContext>(ctx);
	}

	std::string log_level;
	std::string log_id;
	std::vector<parameter_type_t> parameters;
};

} } }

#endif /* ZILLIANS_LANGUAGE_ERRORINFOCONTEXT_H_ */
